### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by fiepfiep** [thocoo/gamma-desk#13] opened 2022-10-28 19:34 UTC
windows 11, python 3.9.6 (also tried with 3.10.8) and pyside6. 
```

PS C:\Users\pbae.OFFICE> python -m gdesk
Bootpath: C:\Users\pbae.OFFICE
Loading config: C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdesk\config\defaults.jsonconfig_files: ['C:\\Users\\pbae.OFFICE/AppData/Local/Gamma-Desk/gdconf.json', 'gdconf.json']
Configfile not found: C:\Users\pbae.OFFICE\AppData\Local\Gamma-Desk\gdconf.json
config_files: ['gdconf.json']
Configfile not found: gdconf.json
Traceback (most recent call last):
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdesk\__main__.py", line 21, in <module>
    shell = argexec()
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdesk\console.py", line 72, in argexec
    configure(**config_kwargs)
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdesk\core\conf.py", line 162, in configure
    from .gui_proxy import gui
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdesk\core\gui_proxy.py", line 15, in <module>
    from ..utils.imconvert import qimage_to_ndarray
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\gdesk\utils\imconvert.py", line 3, in <module>
    from qtpy import QtGui, QtCore
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\site-packages\qtpy\QtCore.py", line 116, in <module>
    Qt.MidButton = Qt.MouseButton.MiddleButton = Qt.MiddleButton
  File "C:\Users\pbae.OFFICE\AppData\Local\Programs\Python\Python39\lib\enum.py", line 472, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.
```

**Comment by louvervecken** [comment] 2022-10-28 19:44
I believe this is an issue caused by incompatibility between qtpy and the latest pyside 6 6.4.0 release. We should pin the pyside version to 6.3.2 until this is fixed by a new qtpy release.

**Comment by fiepfiep** [comment] 2022-10-28 20:08
> I believe this is an issue caused by incompatibility between qtpy and the latest pyside 6 6.4.0 release. We should pin the pyside version to 6.3.2 until this is fixed by a new qtpy release.

indeed, downgrading PySide to 6.3.2 does it.
Thanks Lou!

**Comment by florisla** [comment] 2022-10-31 09:57
The fix ([issue 373](https://github.com/spyder-ide/qtpy/issues/373)) will be in QtPy 2.3.0: https://github.com/spyder-ide/qtpy/milestone/38

**Comment by florisla** [comment] 2022-11-09 18:41
Should be ok now, Qtpy 2.3.0 is out.

**Closed** 2022-11-09 18:41 UTC
